[package]
name = "mars_rover"
version = "0.1.0"
authors = ["Will Munn <will.munn@focusrite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
enum_derive = "0.1.7"
custom_derive = "0.1.7"